CREATE TABLE transmitter (
  id BIGINT AUTO_INCREMENT,
  model VARCHAR(255),
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
);

CREATE TABLE user (
  id BIGINT AUTO_INCREMENT,
  enabled BOOLEAN,
  transmitter_id BIGINT,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (transmitter_id) REFERENCES transmitter (id),
  PRIMARY KEY (id)
);

CREATE TABLE location (
  id BIGINT AUTO_INCREMENT,
  latitude DOUBLE,
  longitude DOUBLE,
  user_id BIGINT,
  gps_timestamp TIMESTAMP NOT NULL,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  FOREIGN KEY (user_id) REFERENCES user (id)
);
